name: dart_pre_commit
description: A small collection of pre commit hooks to format and lint dart code
version: 2.0.0-nullsafety.0
homepage: https://github.com/Skycoder42/dart_pre_commit

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  args: ^1.6.0 # !(test)
  console: ^3.1.0 # X
  convert: ^2.1.1 # !(crypto)
  crypto: ^2.1.5 # !(mockito, build_runner)
  meta: ^1.3.0-nullsafety.6
  path: ^1.8.0-nullsafety.3
  pub_semver: ^1.4.4 # !(cider, build_runner, mockito, test)
  riverpod: ^0.12.2 # X
  yaml: ^3.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.11.0 # X
  # cider: ^0.0.5 # X
  coverage: ^0.15.1 # X
  lint: ^1.5.1
  mockito: ^5.0.0-nullsafety.5
  test: ^1.16.0-nullsafety.16
  tuple: ^1.0.3 # !(mockito)

executables:
  dart_pre_commit: dart_pre_commit
