name: dart_pre_commit
description: A small collection of pre commit hooks to format and lint dart code
version: 2.3.2
homepage: https://github.com/Skycoder42/dart_pre_commit

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.1.1
  console: ^4.1.0
  convert: ^3.0.1
  crypto: ^3.0.1
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  meta: ^1.4.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  riverpod: ^0.14.0+3
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.5
  coverage: ^1.0.3
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3
  mocktail: ^0.1.4
  test: ^1.17.9
  tuple: ^2.0.0

executables:
  dart_pre_commit: dart_pre_commit
