name: dart_pre_commit
description: A small collection of pre commit hooks to format and lint dart code
version: 2.2.0-nullsafety.1
homepage: https://github.com/Skycoder42/dart_pre_commit

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  args: ^2.0.0
  console: ^3.1.0 # X
  convert: ^3.0.0
  crypto: ^3.0.0
  freezed_annotation: ^0.13.0-nullsafety.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  riverpod: ^0.13.0-nullsafety.3
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^1.11.1 # X
  # cider: ^0.0.5 # X
  coverage: ^0.15.2 # X
  freezed: ^0.13.0-nullsafety.2
  json_serializable: ^4.0.0
  lint: ^1.5.1
  mockito: ^5.0.0-nullsafety.7
  test: ^1.16.2
  tuple: ^2.0.0-nullsafety.0

executables:
  dart_pre_commit: dart_pre_commit
