name: dart_pre_commit
description: A small collection of pre commit hooks to format and lint dart code
version: 1.1.4
homepage: https://github.com/Skycoder42/dart_pre_commit

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^1.6.0
  convert: ^2.1.1
  crypto: ^2.1.5
  meta: ^1.2.3
  path: ^1.7.0
  pub_semver: ^1.4.4
  yaml: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.4
  cider: ^0.0.5
  coverage: ^0.14.2
  lint: ^1.3.0
  mockito: ^4.1.3
  test: ^1.15.3
  tuple: ^1.0.3

executables:
  dart_pre_commit: dart_pre_commit
