name: dart_pre_commit
description: A small collection of pre commit hooks to format and lint dart code
version: 1.1.3
homepage: https://github.com/Skycoder42/dart_pre_commit

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0
  crypto: ^2.1.5
  yaml: ^2.2.1
  meta: ^1.2.3
  args: ^1.6.0
  convert: ^2.1.1
  pub_semver: ^1.4.4

dev_dependencies:
  lint: ^1.3.0
  test: ^1.15.3
  mockito: ^4.1.3
  cider: ^0.0.5
  tuple: ^1.0.3
  coverage: ^0.14.2

executables:
  dart_pre_commit: dart_pre_commit
