name: dart_pre_commit
description: A small collection of pre commit hooks to format and lint dart code
version: 2.1.0-nullsafety.0
homepage: https://github.com/Skycoder42/dart_pre_commit

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  args: ^1.6.0 # !(test?, mockito, coverage)
  console: ^3.1.0 # X
  convert: ^3.0.0-nullsafety.0
  crypto: ^3.0.0-nullsafety.0
  freezed_annotation: ^0.13.0-nullsafety.0
  json_annotation: ^4.0.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6
  path: ^1.8.0-nullsafety.3
  pub_semver: ^1.4.4 # !(build_runner)
  riverpod: ^0.13.0-nullsafety.0
  yaml: ^3.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.11.0 # X
  # cider: ^0.0.5 # X
  coverage: ^0.15.1 # X
  freezed: ^0.13.0-nullsafety.2
  json_serializable: ^4.0.0-nullsafety.0
  lint: ^1.5.1
  mockito: ^5.0.0-nullsafety.5
  test: ^1.16.0-nullsafety.17
  tuple: ^2.0.0-nullsafety.0

executables:
  dart_pre_commit: dart_pre_commit
